function p = nomotoParams(setName)
% NOMOTOPARAMS  1차 Nomoto 모델 파라미터 세트 (문헌 출처 명시).
%
%   p = nomotoParams()              기본 세트 반환
%   p = nomotoParams('mariner')     특정 세트 반환
%   nomotoParams('list')            사용 가능한 세트 목록 출력
%
%   모델:  T * rdot + r = K * delta,   psidot = r
%
%   ⚠ 어떤 세트를 이 프로젝트의 플랜트로 채택할지는 아직 결정되지 않았다.
%     docs/decisions.md 의 D-004 (OPEN) 참조. 결정 전까지 기본값은 'mariner' 이며,
%     이는 "문헌에 K, T 가 1차 Nomoto 형태로 직접 명시된 유일한 세트"라는
%     이유로 임시 지정한 것이다. 대상 선박 선정은 작업자가 결정한다.
%
%   반환 구조체 필드:
%     .name        세트 이름
%     .K           Nomoto 이득       [1/s]        (delta 입력 기준 세트만)
%     .T           Nomoto 시상수     [s]
%     .inputType   'rudder_angle' | 'yaw_moment'
%     .Kunit       K 의 물리 단위 문자열
%     .L, .U       기준 선체 길이 [m], 기준 속력 [m/s]
%     .actuator    구동기 제한 (아래 참조)
%     .source      출처 문자열
%     .notes       주의사항
%
%   구동기(actuator) 필드:
%     .enable        true 이면 타각 포화/변화율 제한 적용
%     .deltaMax      최대 타각        [rad]
%     .deltaRateMax  최대 타각 변화율 [rad/s]
%     .Tdelta        타기 1차 지연 시상수 [s]
%
%   See also nomotoDerivative, simulateHeading.

if nargin < 1 || isempty(setName)
    setName = 'mariner';
end

sets = localSets();

if strcmpi(setName, 'list')
    names = fieldnames(sets);
    fprintf('사용 가능한 Nomoto 파라미터 세트:\n');
    for i = 1:numel(names)
        s = sets.(names{i});
        fprintf('  %-10s  K = %+9.5f [%s], T = %+8.2f s   (%s)\n', ...
            s.name, s.K, s.Kunit, s.T, s.inputType);
    end
    p = names;
    return
end

key = lower(setName);
if ~isfield(sets, key)
    error('nomotoParams:unknownSet', ...
        '알 수 없는 파라미터 세트 "%s". nomotoParams(''list'') 로 목록 확인.', setName);
end

p = sets.(key);

end

% ------------------------------------------------------------------------
function sets = localSets()

d2r = pi/180;

% --- 세트 1: Mariner 급 화물선 --------------------------------------------
% 2차 Nomoto 계수 T1, T2, T3, K 로부터 1차 등가 시상수를 계산한다.
%   T = T1 + T2 - T3
sets.mariner = struct( ...
    'name',      'mariner', ...
    'K',         0.185, ...
    'T',         118 + 7.8 - 18.5, ...          % = 107.3 s
    'inputType', 'rudder_angle', ...
    'Kunit',     '(deg/s)/deg = 1/s', ...
    'L',         160.93, ...
    'U',         7.7175, ...                     % 15 knots
    'T1',        118, ...
    'T2',        7.8, ...
    'T3',        18.5, ...
    'actuator',  struct( ...
        'enable',       true, ...
        'deltaMax',     40 * d2r, ...
        'deltaRateMax',  5 * d2r, ...
        'Tdelta',       1.0), ...
    'source', [ ...
      'K, T1, T2, T3: Fossen, MSS (Marine Systems Simulator), ' ...
      'mssExamples/exNomoto.m, github.com/cybergalactic/MSS (2026-08-07 확인). ' ...
      '원 출처: M. S. Chislett and J. Stroem-Tejsen (1965), "Planar Motion ' ...
      'Mechanism Tests and Full-Scale Steering and Maneuvering Predictions ' ...
      'for a Mariner Class Vessel", Report Hy-5, Hydro- and Aerodynamics ' ...
      'Laboratory, Lyngby, Denmark. | L, U0: MSS CRAFT/SHIP/models/mariner.m ' ...
      '| 구동기 제한 40 deg / 5 deg/s: 동 파일 (IMO 35 deg rudder execute 대응).'], ...
    'notes', [ ...
      'L = 160.93 m 화물선. 이 프로젝트의 대상(USV)과 규모가 다르다. ' ...
      '침로 안정(K > 0, T > 0).']);

% --- 세트 2: 유조선 (침로 불안정) ------------------------------------------
sets.tanker = struct( ...
    'name',      'tanker', ...
    'K',         -0.019, ...
    'T',         -124.1 + 16.4 - 46.0, ...       % = -153.7 s
    'inputType', 'rudder_angle', ...
    'Kunit',     '(deg/s)/deg = 1/s', ...
    'L',         NaN, ...
    'U',         NaN, ...
    'T1',        -124.1, ...
    'T2',        16.4, ...
    'T3',        46.0, ...
    'actuator',  struct( ...
        'enable',       true, ...
        'deltaMax',     35 * d2r, ...
        'deltaRateMax',  3 * d2r, ...
        'Tdelta',       1.0), ...
    'source', [ ...
      'Fossen, MSS, mssExamples/exNomoto.m ("Oil tanker"), ' ...
      'github.com/cybergalactic/MSS (2026-08-07 확인). ' ...
      '구동기 제한은 MSS 에 명시되지 않아 통상값을 가정 — 사용 시 출처 보완 필요.'], ...
    'notes', [ ...
      'T < 0 이므로 침로 불안정선. 1단계 대상이 아니며, 3단계 이후 ' ...
      '게인 강건성 비교용 대조군으로만 후보. 구동기 제한값은 미검증.']);

% --- 세트 3: Otter USV (Maritime Robotics) --------------------------------
% MSS 의 Otter 침로 오토파일럿은 요 모멘트 tau_N 을 입력으로 하는
% Nomoto 형태를 쓴다:  T * rdot + r = K * tau_N,  K = T / M(6,6).
% M(6,6) = 40.4938 kg*m^2 (mp = 25 kg, rp = [0 0 0]) 로 계산됨.
sets.otter = struct( ...
    'name',      'otter', ...
    'K',         1.0 / 40.49375, ...             % = 0.024695
    'T',         1.0, ...
    'inputType', 'yaw_moment', ...
    'Kunit',     '(rad/s)/(N*m) = 1/(kg*m^2)', ...
    'L',         2.0, ...
    'U',         6 * 0.5144, ...                 % 6 knots 최대 전진속력
    'T1',        NaN, 'T2', NaN, 'T3', NaN, ...
    'actuator',  struct( ...
        'enable',       false, ...
        'deltaMax',     Inf, ...
        'deltaRateMax', Inf, ...
        'Tdelta',       1.0), ...
    'source', [ ...
      'T = 1 s 및 K = T / M(6,6): Fossen, MSS, CRAFT/USV/SIMotter.m ' ...
      '(97-99행), github.com/cybergalactic/MSS (2026-08-07 확인). ' ...
      'M(6,6) = 40.4938 kg*m^2 는 CRAFT/USV/models/otter.m 의 ' ...
      'MRB + MA 구성을 mp = 25 kg, rp = [0 0 0] 조건으로 재계산해 확인. ' ...
      '주요 제원 L = 2.0 m, B = 1.08 m, m = 55 kg: 동 파일.'], ...
    'notes', [ ...
      '⚠ 입력이 타각(delta)이 아니라 요 모멘트(tau_N)다. Otter 는 차동추진 ' ...
      'USV 라 물리적 러더가 없다. HANDOFF 의 T*rdot + r = K*delta 형태와 ' ...
      '단위가 다르므로, 이 세트를 쓰려면 "러더 사용량" 지표의 정의를 ' ...
      '모멘트 기준으로 다시 정해야 한다. ' ...
      '또한 T = 1 s 는 문헌 동정값이 아니라 MSS 오토파일럿 설계에서 ' ...
      '가정한 값이다 (K 를 T 로부터 역산). 동정 실험 기반 값이 아님.']);

end
